/* Generated by hand for the EwokOS port: cmake's GenerateExportHeader would
   normally write this.  qtermwidget is linked statically into qterminal, so
   the visibility macros are all empty. */

#ifndef QTERMWIDGET_EXPORT_H
#define QTERMWIDGET_EXPORT_H

#define QTERMWIDGET_EXPORT
#define QTERMWIDGET_NO_EXPORT
#define QTERMWIDGET_DEPRECATED
#define QTERMWIDGET_DEPRECATED_EXPORT
#define QTERMWIDGET_DEPRECATED_NO_EXPORT

#endif /* QTERMWIDGET_EXPORT_H */
