/* Generated by hand for the EwokOS port from qtermwidget_version.h.in
   (cmake would normally substitute these; the vendored snapshot is 1.4.0). */

#ifndef _Q_TERM_WIDGET_VERSION
#define _Q_TERM_WIDGET_VERSION

#include <QtGlobal>
#define QTERMWIDGET_VERSION_MAJOR 1
#define QTERMWIDGET_VERSION_MINOR 4
#define QTERMWIDGET_VERSION_PATCH 0
#define QTERMWIDGET_VERSION QT_VERSION_CHECK(\
        QTERMWIDGET_VERSION_MAJOR,\
        QTERMWIDGET_VERSION_MINOR,\
        QTERMWIDGET_VERSION_PATCH)

#endif
